CATEGORIES = {
    "spam": {
        "priority": 1,
        "keywords": [
            "выигр", "vyigr",
            "побед", "pobed",
            "розыгр", "rozygr",
            "приз", "priz",
            "данные карты", "dannye karty",
            "банковской карты", "bankovskoy karty",
            "перейдите по ссылке", "pereydite po ssylke",
            "подозрительный вход", "podozritelnyy vkhod",
            "exclusive offer",
            "limited time",
            "только сегодня", "tolko segodnya",
            "эксклюзив", "eksklyuziv",
            "скидка", "skidka",
            "поздравляем", "pozdravlyaem",
            "congratulations",
        ],
    },
    "draft": {
        "priority": 2,
        "keywords": [
            "черновик", "chernovik",
            "draft",
            "не отправлять", "ne otpravlyat",
            "to do",
            "todo",
        ],
    },
    "critical": {
        "priority": 3,
        "keywords": [
            "критичн", "kritichn",
            "критическ", "kritichesk",
            "critical",
            "warning",
            "urgent",
            "срочн", "srochn",
            "immediately",
            "инцидент", "intsident",
            "outage",
            "упал", "upal",
        ],
    },
    "software_issues": {
        "priority": 4,
        "keywords": [
            "не запуск", "ne zapusk",
            "не откры", "ne otkry",
            "перестал запуск", "perestal zapusk",
            "ошибк", "oshibk",
            "сбой", "sboy",
            "недоступен", "nedostupen",
            "не отвеч", "ne otvech",
            "остановл", "ostanovl",
            "затронут", "zatronut",
            "переустан", "pereуstan",
            "после обновл", "posle obnovl",
            "доступ запрещен", "dostup zapreshchen",
            "нет доступа", "net dostupa",
            "заблокирован", "zablokirovan",
            "пропал доступ", "propal dostup",
            "не могу войти", "ne mogu voyti",
            "запрос доступа", "zapros dostupa",
            "восстановить доступ", "vosstanovit dostup",
            "нужны права", "nuzhny prava",
            "выдать доступ", "vydat dostup",
            "unauthorized",
            "error",
            "код ошибки", "kod oshibki",
            "не работает", "ne rabotaet",
            "вылетает", "vyletaet",
            "зависает", "zavisaet",
            "падает", "padaet",
            "упал", "upal",
            "баг", "bag",
            "bug",
            "сбой авторизации", "sboy avtorizatsii",
            "не открыв", "ne otkryv",
        ],
    },
    "hardware_issues": {
        "priority": 5,
        "keywords": [
            "принтер", "printer",
            "сканер", "skaner",
            "ноутбук", "noutbuk",
            "гарнитура", "garnitura",
            "мышь", "mysh",
            "монитор", "monitor",
            "клавиатур", "klaviatur",
            "экран", "ekran",
            "компьютер", "kompyuter",
            "процессор", "protsessor",
            "жесткий диск", "zhestkiy disk",
            "ссд", "ssd",
            "ssd",
            "не вкл", "ne vkl",
            "слом", "slom",
            "неисправ", "neisprav",
            "ремонт", "remont",
            "замен", "zamen",
            "диагностик", "diagnostik",
            "устройств", "ustroystvo",
            "симптом", "simptom",
            "после падения", "posle padeniya",
            "посторонние звуки", "postoronnie zvuki",
            "не определяется", "ne opredelyaetsya",
            "оборудов", "oborudov",
        ],
    },
    "financial_requests": {
        "priority": 6,
        "keywords": [
            "счёт", "schyot",
            "счет", "schet",
            "invoice",
            "плат", "plat",
            "документ", "dokument",
            "акт", "akt",
            "договор", "dogovor",
            "бухгалтер", "bukhgalter",
            "задолжен", "zadolzhen",
            "платёж", "platyozh",
            "платеж", "platezh",
            "оказанные услуги", "okazannye uslugi",
            "уточнение по оплате", "utochneniye po oplate",
            "статус", "status",
            "финанс", "finans",
            "budget",
            "payment",
            "billing",
            "реквизит", "rekvizit",
        ],
    },
    "meeting_requests": {
        "priority": 7,
        "keywords": [
            "звон", "zvon",
            "встреч", "vstrech",
            "встрет", "vstret",
            "обсу", "obsu",
            "демо", "demo",
            "demo",
            "пригла", "prigla",
            "перенос", "perenos",
            "zoom",
            "teams",
            "meet",
            "invite",
            "calendar",
            "schedule",
            "расписани", "raspisani",
            "интервью", "intervyu",
            "interview",
        ],
    },
    "informational": {
        "priority": 8,
        "keywords": [
            "автомат", "avtomat",
            "высылаем", "vysylaem",
            "направляем", "napravlyaem",
            "info",
            "информа", "informa",
            "отчёт", "otchyot",
            "отчет", "otchet",
            "мониторинг", "monitoring",
            "дайджест", "daydzhest",
            "newsletter",
            "news",
            "итог", "itog",
            "политик", "politik",
            "объявлен", "obyavlen",
            "announcement",
            "новый сотрудник", "novyy sotrudnik",
            "больн", "boln",
            "болен", "bolen",
            "нетрудоспособ", "netrudosposob",
            "отпуск", "otpusk",
            "график", "grafik",
            "рабочее место", "rabocheye mesto",
            "оформ", "oform",
            "метрик", "metrik",
            "технические работы", "tekhnicheskiye raboty",
            "плановые работы", "planovyye raboty",
        ],
    },
}